openapi: 3.0.3
info:
  title: ACME Test
  version: "1.0"
servers:
  - url: http://localhost:8080
    description: Localhost
paths:
  /foo:
    get:
      summary: Get all current Affected Vulnerabilities
      description: Returns all current Affected Vulnerabilities
      operationId: getVulns
      parameters:
        - name: bar
          in: query
          description: id of bar
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
              